# Generated by Django 5.0.2 on 2024-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_news_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.FileField(default=True, max_length=250, null=True, upload_to='news/'),
        ),
    ]
